"""Spinner animation frames and whimsical verb list.

Character sequence sourced from Claude Code's CLI (character values only,
no code copied). The spinner cycles through six star/asterisk-like glyphs
in Claude's brand orange color. The verb text shares the same color.
"""

# Star/asterisk spinner frames (6 frames, cycle at ~80ms each)
SPINNER_FRAMES = ["·", "✢", "✳", "∗", "✻", "✽"]

# Interval between spinner frames in milliseconds
SPINNER_INTERVAL_MS = 80

# Spinner color — Claude's warm orange/terracotta (brand color)
SPINNER_COLOR = "#da7756"

# Whimsical verbs displayed alongside the spinner
SPINNER_VERBS = [
    "Accomplishing",
    "Architecting",
    "Baking",
    "Beboppin'",
    "Boogieing",
    "Booping",
    "Brewing",
    "Calculating",
    "Cascading",
    "Cerebrating",
    "Churning",
    "Clauding",
    "Coalescing",
    "Cogitating",
    "Combobulating",
    "Composing",
    "Computing",
    "Concocting",
    "Contemplating",
    "Cooking",
    "Crafting",
    "Creating",
    "Crunching",
    "Crystallizing",
    "Deliberating",
    "Determining",
    "Discombobulating",
    "Doing",
    "Enchanting",
    "Envisioning",
    "Fermenting",
    "Finagling",
    "Flowing",
    "Forging",
    "Forming",
    "Gallivanting",
    "Generating",
    "Grooving",
    "Harmonizing",
    "Hashing",
    "Hatching",
    "Ideating",
    "Imagining",
    "Improvising",
    "Incubating",
    "Inferring",
    "Levitating",
    "Manifesting",
    "Meandering",
    "Metamorphosing",
    "Moonwalking",
    "Mulling",
    "Musing",
    "Noodling",
    "Orchestrating",
    "Percolating",
    "Philosophising",
    "Pondering",
    "Pontificating",
    "Processing",
    "Proofing",
    "Puzzling",
    "Razzle-dazzling",
    "Recombobulating",
    "Ruminating",
    "Simmering",
    "Sketching",
    "Spinning",
    "Sprouting",
    "Synthesizing",
    "Thinking",
    "Tinkering",
    "Transmuting",
    "Undulating",
    "Vibing",
    "Wandering",
    "Whirring",
    "Working",
    "Wrangling",
    "Zigzagging",
]
