#!/usr/bin/env python3
"""Generate a license audit JSON for production Python dependencies.

Parses pyproject.toml for dependency names and runs pip-licenses to
collect license metadata.

Usage:
    just licenses
    uv run scripts/generate_licenses.py
"""

import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PYPROJECT = ROOT / "pyproject.toml"
OUTPUT = ROOT / "3rd_party_licenses.txt"

# Packages that are CLI tool wrappers, not linked dependencies —
# exclude from license audit.
EXCLUDE_PACKAGES = {"gifsicle-bin"}


def parse_production_deps(pyproject_path: Path) -> list[str]:
    """Extract production dependency names from pyproject.toml."""
    content = pyproject_path.read_text()
    lines = content.split("\n")

    packages = []
    in_dependencies = False

    for line in lines:
        stripped = line.strip()

        if stripped.startswith("dependencies") and "=" in stripped:
            in_dependencies = True
            continue

        if in_dependencies and stripped == "]":
            break

        if not in_dependencies:
            continue

        if not stripped or stripped.startswith("#"):
            continue

        dep = stripped.strip(",").strip('"').strip("'")

        # Skip URL-based dependencies
        if "@" in dep:
            continue

        pkg_match = re.match(r"([a-zA-Z0-9_-]+)", dep)
        if pkg_match:
            packages.append(pkg_match.group(1))

    return packages


def main():
    packages = [
        p for p in parse_production_deps(PYPROJECT) if p not in EXCLUDE_PACKAGES
    ]
    if not packages:
        print("No packages found in pyproject.toml", file=sys.stderr)
        sys.exit(1)

    print(f"Analyzing licenses for {len(packages)} packages: {', '.join(packages)}")

    result = subprocess.run(
        [
            sys.executable,
            "-m",
            "piplicenses",
            "--format",
            "plain-vertical",
            "--with-license-file",
            "--no-license-path",
            "--packages",
            *packages,
        ],
        capture_output=True,
        text=True,
    )

    if result.returncode != 0:
        print(f"Error: {result.stderr}", file=sys.stderr)
        print("Install pip-licenses: uv pip install pip-licenses", file=sys.stderr)
        sys.exit(1)

    # Prepend bundled (non-pip) assets, then append pip-licenses output
    header = (
        "Third-party licenses for agent-log-gif\n"
        "=======================================\n"
        "\n"
        "This file is auto-generated by: just licenses\n"
        "\n"
        "== Bundled assets (non-pip) ==\n"
        "\n"
        "DejaVu Sans Mono font\n"
        "  License: Bitstream Vera\n"
        "  See: src/agent_log_gif/fonts/DejaVuSansMono-LICENSE.txt\n"
        "\n"
        "iTerm2-Color-Schemes color data\n"
        "  License: MIT (Copyright (c) 2011 to Present Mark Badolato)\n"
        "  Source: https://github.com/mbadolato/iTerm2-Color-Schemes\n"
        "  See: src/agent_log_gif/color_schemes_LICENSE.txt\n"
        "\n"
        "== Python dependencies ==\n"
        "\n"
    )

    OUTPUT.write_text(header + result.stdout)
    print(f"Wrote {OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
